// Generated by cpp.py
#include <cstdio>
#include <string>
#include <cstdarg>

#define print printf
#define str   std::string   
/* Start */
int main() {
    int x = 0;
    while (x < 100) {
        if (x % 5 == 0 && x % 3 == 0) {
            print("Fizzbuzz\n");
        } else if (x % 3 == 0) {
            print("Fizz\n");
        } else if (x % 5 == 0) {
            print("Buzz\n");
        } else {
            print("%d\n", x);
        }
        x += 1;
    }
}